export const baseThemeVariables = {
  primary: '#3366ff',
  success: '#00d68f',
  info: '#0095ff',
  warning: '#ffaa00',
  danger: '#ff3d71',
  bg: '#ffffff',
  bg2: '#f7f9fc',
  bg3: '#edf1f7',
  bg4: '#e4e9f2',
  fg: '#222b45',
  fgText: '#222b45',
  fgHighlight: '#3366ff',
  border: '#edf1f7',
  border2: '#e4e9f2',
  border3: '#c5cee0',
  border4: '#8f9bb3',
  border5: '#2e3a59',
  separator: '#edf1f7',
  divider: '#edf1f7',
  textHint: '#8f9bb3',
  textControl: '#ffffff',
  warningLight: '#ffcc66',
  infoLight: '#66c2ff',
  dangerLight: '#ff85a2',
  successLight: '#52ffbd',
  primaryLight: '#85a7ff',

  // Added for components that expect these variables
  fontMain: 'Open Sans, sans-serif',
  fontSecondary: 'Raleway, sans-serif',
  fgHeading: '#222b45',

  echarts: {
    bg: '#ffffff',
    textColor: '#222b45',
    axisLineColor: '#edf1f7',
    splitLineColor: '#edf1f7',
    itemHoverShadowColor: 'rgba(0, 0, 0, 0.5)',
    tooltipBackgroundColor: '#ffffff',
    areaOpacity: '0.7',
  },

  temperature: {
    arcEmpty: '#edf1f7',
    arcFill: ['#3366ff', '#3366ff', '#3366ff', '#3366ff', '#3366ff'],
    thumbBg: '#ffffff',
    thumbBorder: '#3366ff',
  },
  solar: {
    radius: ['70%', '90%'],
    gradientLeft: '#3366ff',
    gradientRight: '#3366ff',
    shadowColor: 'rgba(0, 0, 0, 0)',
    secondSeriesFill: '#edf1f7',
  },
  traffic: {
    colorPlugin: '#3366ff',
    lineBg: '#edf1f7',
    lineShadow: '#3366ff',
    gradFrom: '#3366ff',
    gradTo: '#3366ff',
    itemColor: '#3366ff',
    itemBorderColor: '#3366ff',
    itemEmphasisBorderColor: '#3366ff',
    shadowLineDarkBg: '#edf1f7',
    shadowStatDarkBg: '#edf1f7',
    shadowLineShadow: '#3366ff',
    shadowStatShadow: '#3366ff',
    yAxisSplitLine: '#edf1f7',
    tooltipBg: '#ffffff',
    tooltipBorderColor: '#edf1f7',
    tooltipTextColor: '#222b45',
    tooltipFontWeight: '600',
    tooltipExtraCss: '',
    lineShadowBlur: '0',
    echarts: {
      tooltipBackgroundColor: '#ffffff',
      tooltipBorderColor: '#edf1f7',
      tooltipTextColor: '#222b45',
      tooltipFontSize: '12',
      tooltipLineColor: '#edf1f7',
      tooltipLineWidth: '1',
      tooltipLineType: 'solid',
      tooltipLineShadow: 'rgba(0, 0, 0, 0)',
      tooltipLineShadowBlur: '0',
      tooltipLineShadowOffsetX: '0',
      tooltipLineShadowOffsetY: '0',
    },
  },
  electricity: {
    tooltipBg: '#ffffff',
    tooltipLineColor: '#edf1f7',
    tooltipLineWidth: '1',
    chartLineColor: '#3366ff',
    chartBackGradientFrom: '#3366ff',
    chartBackGradientTo: '#3366ff',
    chartPrimaryGradientFrom: '#3366ff',
    chartPrimaryGradientTo: '#3366ff',
    chartSecondaryGradientFrom: '#3366ff',
    chartSecondaryGradientTo: '#3366ff',
    chartThirdGradientFrom: '#3366ff',
    chartThirdGradientTo: '#3366ff',

    tooltipTextColor: '#222b45',
    tooltipFontWeight: '600',
    tooltipBorderColor: '#edf1f7',
    tooltipExtraCss: '',
    xAxisTextColor: '#222b45',
    axisLineColor: '#edf1f7',
    yAxisSplitLine: '#edf1f7',
    itemBorderColor: '#3366ff',
    lineWidth: '2',
    lineStyle: 'solid',
    lineGradFrom: '#3366ff',
    lineGradTo: '#3366ff',
    lineShadow: 'rgba(0, 0, 0, 0)',
    areaGradFrom: '#3366ff',
    areaGradTo: '#3366ff',
    shadowLineDarkBg: '#edf1f7',
  },
};

export const DEFAULT_THEME = {
  name: 'default',
  variables: baseThemeVariables,
};

export const COSMIC_THEME = {
  name: 'cosmic',
  variables: {
    ...baseThemeVariables,
    bg: '#222b45',
    bg2: '#1a2138',
    bg3: '#151a30',
    fg: '#ffffff',
    fgText: '#ffffff',
    border: '#2e3a59',
    divider: '#2e3a59',
    echarts: {
      ...baseThemeVariables.echarts,
      bg: '#222b45',
      textColor: '#ffffff',
      axisLineColor: '#2e3a59',
      splitLineColor: '#2e3a59',
      tooltipBackgroundColor: '#1a2138',
    },
  },
};

export const CORPORATE_THEME = {
  name: 'corporate',
  variables: {
    ...baseThemeVariables,
    bg2: '#f2f6ff',
    bg3: '#dbe4ff',
    border: '#d6deff',
    divider: '#d6deff',
  },
};

export const DARK_THEME = {
  name: 'dark',
  variables: {
    ...COSMIC_THEME.variables,
  },
};
